// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// R_ocr
String R_ocr(RawVector input, std::string format);
RcppExport SEXP tesseract_R_ocr(SEXP inputSEXP, SEXP formatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< std::string >::type format(formatSEXP);
    __result = Rcpp::wrap(R_ocr(input, format));
    return __result;
END_RCPP
}
