// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ocr_file
String ocr_file(std::string filename);
RcppExport SEXP tesseract_ocr_file(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(ocr_file(filename));
    return rcpp_result_gen;
END_RCPP
}
// ocr_raw
String ocr_raw(RawVector input);
RcppExport SEXP tesseract_ocr_raw(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(ocr_raw(input));
    return rcpp_result_gen;
END_RCPP
}
