# Generated by cpp11: do not edit by hand

tesseract_config <- function() {
  .Call(`_tesseract_tesseract_config`)
}

tesseract_engine_internal <- function(datapath, language, confpaths, opt_names, opt_values) {
  .Call(`_tesseract_tesseract_engine_internal`, datapath, language, confpaths, opt_names, opt_values)
}

tesseract_engine_set_variable <- function(ptr, name, value) {
  .Call(`_tesseract_tesseract_engine_set_variable`, ptr, name, value)
}

validate_params <- function(params) {
  .Call(`_tesseract_validate_params`, params)
}

engine_info_internal <- function(ptr) {
  .Call(`_tesseract_engine_info_internal`, ptr)
}

print_params <- function(filename) {
  .Call(`_tesseract_print_params`, filename)
}

get_param_values <- function(api, params) {
  .Call(`_tesseract_get_param_values`, api, params)
}

ocr_raw <- function(input, ptr, HOCR) {
  .Call(`_tesseract_ocr_raw`, input, ptr, HOCR)
}

ocr_file <- function(file, ptr, HOCR) {
  .Call(`_tesseract_ocr_file`, file, ptr, HOCR)
}

ocr_raw_data <- function(input, ptr) {
  .Call(`_tesseract_ocr_raw_data`, input, ptr)
}

ocr_file_data <- function(file, ptr) {
  .Call(`_tesseract_ocr_file_data`, file, ptr)
}
