# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_ocr <- function(input, format) {
    .Call('tesseract_R_ocr', PACKAGE = 'tesseract', input, format)
}

